### ISSUE TITLE
Difference between `libstripe` and `stripe-rust`

### ISSUE THREAD

**Issue by daniel-abramov** [bundleofbytes/libstripe#3]
Hi,

I've noticed that among crates which provide `Stripe` API implementation, there are only 2 non-obsolete crates:

1. `stripe-rust` (a.k.a. `stripe-rs`).
2. `libstripe`.

I've noticed that `libstripe` was created a couple months later after `stripe-rust`. I analyzed the docs for both of the crates and shortly checked the usage. For the most part, both crates look very similar. I'm just wondering if there was a reason to create `libstripe`. It seems for me that it would make sense to combine efforts and contribute to one crate, as both provide very similar (if not same) functionality and even the semantics and organization (split to `async` and `sync` via `reqwest`) looks almost the same.

**Comment by dariusc93** [comment]
For the most part they both are similar. Some of it was inspired by `stripe-rust` while doing a big rewrite of the crate a couple of years ago (things were kept simple initially) before publishing it, but it made a bit more sense at the time to create `libstripe` than to depend on another crate since I had different views on a few things as well as was being focused on keep it up to date with stripe documents as much as possible. I believe at the time they were also using a different version of stripe api while I was using something much later so that could also be a bit conflicting.

While I wouldnt mind on having just one crate, I do have plans with this one that may not be suited with merging with another just yet until it is completed.

**Comment by daniel-abramov** [comment]
Alright, got it. I was just asking that, because as a developer who searches for Stripe crates, there are 2 almost equal choices and when the team decides on the new dependency when 2 of them seem to be very similar, they tend to choose the one which seems to be more "actively developed" (`stripe-rust` seems to have "bigger" community). I think that both crates are good, but I also see that they are very similar (if not same) and so when I consider the contributions to one or another, it's sometimes hard to decide which to choose.

But anyway, thanks for the quick response.
